In [1]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
arr=np.array([[1,2,3,],[4,2,5]])
type(arr)

numpy.ndarray

In [4]:
my_list=[1,2,3,4,5]

In [5]:
my_list

[1, 2, 3, 4, 5]

In [6]:
np.array(my_list)

array([1, 2, 3, 4, 5])

In [7]:
#matrics  
my_matrix=[[1,2,3],[4,5,6],[7,8,9],[1,23,4]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 23, 4]]

In [8]:
mat=np.array(my_matrix)
mat

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 1, 23,  4]])

In [9]:
#shape
mat.shape

(4, 3)

In [10]:
#Built in methos 

In [11]:
#1-arrange

In [14]:
f = np.arange(0, 30, 5)

In [15]:
f

array([ 0,  5, 10, 15, 20, 25])

In [19]:
f=np.arange(0,100,5)

In [20]:
f

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [21]:
#2-linspace
g=np.linspace(0,5,10)
g

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [22]:
#3-eye or identity
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
#4-Random
np.random.rand(1)

array([0.24461493])

In [26]:
np.random.randn(10)

array([-0.88205719, -0.87084304,  0.4869729 , -0.77006525,  3.00527156,
        0.54740667, -1.45680393, -1.18017092,  1.36123022,  0.25587441])

In [27]:
np.random.randint(0,1000,10)

array([960, 895, 234, 661, 173, 509,  73, 607, 308, 411])

In [28]:
#5-Reshape
arr=np.array([[1,2,3,4],[4,6,7,8],[1,2,0,7]])

In [33]:
newarr=arr.reshape(2,2,3)
print("Original array:\n",arr)
print("----------------------")
print("Reshaped array:\n",newarr)

Original array:
 [[1 2 3 4]
 [4 6 7 8]
 [1 2 0 7]]
----------------------
Reshaped array:
 [[[1 2 3]
  [4 4 6]]

 [[7 8 1]
  [2 0 7]]]
