In [1]:
import numpy as np

In [2]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [4]:
#Show
np.mean(arr)

15.5

In [5]:
#1D array
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [6]:
arr[:3]

array([11, 12, 13])

In [7]:
arr[-5:]

array([16, 17, 18, 19, 20])

In [8]:
l=np.array([1,2,3])
l1=np.array([4,5,6])

In [9]:
l+l1

array([5, 7, 9])

In [10]:
l*l1

array([ 4, 10, 18])

In [11]:
l-l1

array([-3, -3, -3])

In [12]:
l/l1

array([0.25, 0.4 , 0.5 ])

In [13]:
arr=np.arange(0,9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
arr*2

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [15]:
arr*3

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [16]:
arr+arr

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [17]:
arr*arr

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [18]:
arr-arr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [20]:
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [21]:
b=np.array([[11,12],[13,14]])
b

array([[11, 12],
       [13, 14]])

In [22]:
a*b

array([[11, 24],
       [39, 56]])

In [23]:
#square root 
np.sqrt(arr)

array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712]])

In [24]:
#exponential
np.exp(2)

7.38905609893065

In [25]:
np.exp(5)

148.4131591025766

In [26]:
np.max(arr)

8

In [27]:
np.mean(arr)

4.0

In [28]:
np.cos(arr)

array([[ 1.        ,  0.54030231, -0.41614684],
       [-0.9899925 , -0.65364362,  0.28366219],
       [ 0.96017029,  0.75390225, -0.14550003]])

In [29]:
#log function
np.log(5)

1.6094379124341003

In [30]:
np.log(4)

1.3862943611198906

In [31]:
#function for rounding
z=np.array([1.0,5.55,123,0.5678,25.532])

In [33]:
print('Original array: ')
print(z)
print('\n' )

#print (after rounding)
#print(np.around(z))
print(np.around(z,decimals=1))

Original array: 
[  1.       5.55   123.       0.5678  25.532 ]


[  1.    5.6 123.    0.6  25.5]


In [34]:
np.around(2.351241,0)

2.0